# Generated by Django 5.0.6 on 2024-09-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cropping',
        ),
    ]
