# Generated by Django 5.0.6 on 2024-09-09 17:02

import django.core.validators
import ngo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider_images/', validators=[ngo_app.models.validate_image_size])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
