# Generated by Django 5.0.6 on 2024-09-09 17:13

import ngo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='slider',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='slider',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/', validators=[ngo_app.models.validate_image_size]),
        ),
    ]
