# Generated by Django 5.0.6 on 2024-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0002_slider_alt_text_slider_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=100),
        ),
        migrations.AddField(
            model_name='slider',
            name='item_description',
            field=models.CharField(blank=True, help_text='Description of this slider item (for accessibility and SEO)', max_length=160),
        ),
        migrations.AddField(
            model_name='slider',
            name='item_keywords',
            field=models.CharField(blank=True, help_text='Keywords/tags for this slider item', max_length=255),
        ),
    ]
