# Generated by Django 5.0.6 on 2024-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0003_remove_slider_alt_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('donation_title', models.CharField(max_length=100)),
                ('donation_content', models.TextField()),
                ('volunteer_title', models.CharField(max_length=100)),
                ('volunteer_content', models.TextField()),
                ('image', models.ImageField(help_text='Image should be 1280x720 pixels', upload_to='about_us/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Meta Title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Meta Description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Meta Keywords', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
