# Generated by Django 5.1.1 on 2024-09-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0005_remove_aboutus_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of the video'),
        ),
    ]
