# Generated by Django 5.1.1 on 2024-09-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0006_aboutus_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='video_embed',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of the YouTube video'),
        ),
    ]
