# Generated by Django 5.1.1 on 2024-09-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0008_schemedata_alter_aboutus_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemedata',
            options={},
        ),
    ]
