# Generated by Django 5.0.6 on 2024-09-12 15:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0009_alter_schemedata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
