# Generated by Django 5.0.6 on 2024-09-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0011_donor_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='title',
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='pan_no',
            field=models.CharField(max_length=10),
        ),
    ]
