# Generated by Django 5.0.6 on 2024-09-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0012_remove_donor_title_alter_donor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
