# Generated by Django 5.0.6 on 2024-09-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0014_alter_donor_address_alter_donor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
