# Generated by Django 5.0.6 on 2024-09-17 08:50

import ngo_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0017_alter_donation_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='pan_no',
            field=ngo_app.models.EncryptedField(blank=True, null=True),
        ),
    ]
